# data
data_dir: data/scotus_case
data_name: scotus_case
min_vocab_freq: 1
max_seq_length: 512
include_test_labels: true
add_special_tokens: true
hierarchical: true
accumulate_grad_batches: 4

# train
seed: 1337
epochs: 20
batch_size: 2
optimizer: adamw
learning_rate: 0.00003
weight_decay: 0
patience: 5

# eval
eval_batch_size: 2
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@5', 'RP@5', 'nDCG@5']
val_metric: Micro-F1

# model
model_name: BERT
init_weight: null
network_config:
  lm_weight: bert-base-uncased

# pretrained vocab / embeddings
embed_file: null
