# data
data_dir: data_linear/scotus
data_name: scotus

# train
seed: 1337
linear: true
liblinear_options: "-s 2 -B 1 -e 0.0001 -q"
linear_technique: 1vsrest

# eval
eval_batch_size: 256
monitor_metrics: [Macro-F1, Micro-F1, P@1, P@3, P@5]
metric_threshold: 0

data_format: txt
