# data
data_dir: data/AmazonCat-13K
data_name: AmazonCat-13K
min_vocab_freq: 1
max_seq_length: 512
include_test_labels: false
add_special_tokens: true

# train
seed: 1337
epochs: 12
batch_size: 32
optimizer: adamw
learning_rate: 0.00003
weight_decay: 0
patience: 12
shuffle: true

# eval
eval_batch_size: 32
monitor_metrics: ['P@1', 'P@3', 'P@5', 'RP@5', 'nDCG@5', 'Loss']
val_metric: RP@5

# model
model_name: BERT
init_weight: null
network_config:
  dropout: 0.1
  lm_weight: bert-base-uncased
  lm_window: 512

# pretrained vocab / embeddings
embed_file: null
