# data
data_dir: data/AmazonCat-13K
data_name: AmazonCat-13K
min_vocab_freq: 1
max_seq_length: 500

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 64
monitor_metrics: ['P@1', 'P@3', 'P@5', 'RP@5', 'nDCG@5', 'Loss']
val_metric: RP@5

# model
model_name: KimCNN
init_weight: kaiming_uniform
network_config:
  embed_dropout: 0.2
  encoder_dropout: 0.2
  filter_sizes: [8]
  num_filter_per_size: 1024

# pretrained vocab / embeddings
embed_file: glove.6B.200d
