# data
data_dir: data_linear/ecthr_b
data_name: ecthr_b

# train
seed: 1337
linear: true
liblinear_options: "-s 2 -B 1 -e 0.0001 -q"
linear_technique: 1vsrest

# eval
eval_batch_size: 256
monitor_metrics: [Micro-F1, Macro-F1]
metric_threshold: 0

data_format: txt
